repository_url:
  ce: "git@github.com:magento/magento2.git::2.1"
  ee: ""
  ce_sample_data: "git@github.com:magento/magento2-sample-data.git::2.1"
  ee_sample_data: ""
guest:
  # NFS will be used for folder synchronization on *nix and OSX hosts by default
  use_nfs: 1
  # Default is 2Gb, around 3Gb is necessary to run functional tests
  memory: 2048
  ip_address: "192.168.10.2"
  forwarded_ssh_port: 3000
environment:
  # If set to 0, PHP 5 will be installed
  use_php7: 0
  composer_prefer_source: 0
magento:
  # [To apply changes: m-switch-to-ce -f OR m-switch-to-ee -f]
  install_sample_data: 1
  # [To apply changes: init-project -f]
  host_name: "magento2.vagrant2"
  # [To apply changes: m-reinstall]
  admin_frontname: "admin"
  language: "en_US"
  timezone: "America/Chicago"
  currency: "USD"
  admin_user: "admin"
  admin_password: "123123q"
  # [Changes applied on m-clear-cache] Available options: developer, production, default
  mode: "default"
